// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyHiRSGgrrWVItWnHbutvZBNRt2PQ_OcU',
    appId: '1:288861281734:web:7dae0f2095e8d663c466c7',
    messagingSenderId: '288861281734',
    projectId: 'aadi-electronics-blueberry',
    authDomain: 'aadi-electronics-blueberry.firebaseapp.com',
    storageBucket: 'aadi-electronics-blueberry.firebasestorage.app',
    measurementId: 'G-8DJT7MBH50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAokrg_LbnK6IqetZRDfs8TQY5-CgXL70M',
    appId: '1:288861281734:android:a750d67bdd75b17dc466c7',
    messagingSenderId: '288861281734',
    projectId: 'aadi-electronics-blueberry',
    storageBucket: 'aadi-electronics-blueberry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkK2K0ALXQwOBurtVEyo8pm-PsYjloCmM',
    appId: '1:288861281734:ios:cdb65cefb2be249fc466c7',
    messagingSenderId: '288861281734',
    projectId: 'aadi-electronics-blueberry',
    storageBucket: 'aadi-electronics-blueberry.firebasestorage.app',
    iosBundleId: 'com.aadielectronics.blueberry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyHiRSGgrrWVItWnHbutvZBNRt2PQ_OcU',
    appId: '1:288861281734:web:4f016dcc8ecbda29c466c7',
    messagingSenderId: '288861281734',
    projectId: 'aadi-electronics-blueberry',
    authDomain: 'aadi-electronics-blueberry.firebaseapp.com',
    storageBucket: 'aadi-electronics-blueberry.firebasestorage.app',
    measurementId: 'G-3EGH5GSMSC',
  );
}
